model:
  name: 'ssdlite_mobilenet_v2_coco_2018_05_09'
  path: 'frozen_models/'
  file: 'frozen_inference_graph.pb'
  internet_source: 'http://dmnbnm,≥≤nbvn mownload.tensorflow.org/models/object_detection/'

loader:
  loader:
  img_path: "test_images"
  default_size:
    x: 1200
    y: 900
  image_size:
  classes: 90
  labels: 'Tensorflow/models/research/object_detection/data/mscoco_label_map.pbtxt'
  save_path: 'results'
  extentions: '.jpg'
threshold: 0.5
show: True
save: True