name: ODGUI
dependencies:
    - python=3.6
    - numpy=1.18.*
    - pandas=1.0.*
    - keras=2.3.*
    - tensorflow=1.12.*
    - Pillow=7.0*
    - tensorflow-hub
    - matplotlib=3.1*
    - pip:
          - opencv-python